function props = operatorProperties()
global data
global MaxComponents
global AutoScale
global BalanceBags
global CrossValidation
global Optimization
global Permutations
global SaveClassifier
props = {   'MaxComponents', 10; ...
            'AutoScale', {'No', 'Yes'}; ...
            'BalanceBags', 0; ...
            'CrossValidation',{'LOOCV', '10-fold', '20-fold', 'none'}; ...
            'Optimization', {'auto', 'LOOCV', '10-fold', '20-fold','none'}; ...
            'Permutations', 0; ...
            'SaveClassifier', {'No', 'Yes'}
        };
     
            